version: "3"

services:
  amalgamation:
    build: ./amalgamation
    networks:
      - bridge
    volumes:
      - ./amalgamation:/opt/project
      - ./data:/data
    environment:
      HETSAPI_INTERNAL_URL: hets-api:5000
    depends_on:
      - hets-api

  hets-api:
    build:
      context: ./hets-api
      dockerfile: Dockerfile.dev
    networks:
      - bridge
    ports:
      - "5000:5000"
    volumes:
      - ./hets-api/hets_api:/opt/project/hets_api
      - ./hets-api/tests:/opt/project/tests
      - ./hets-api/setup.py:/opt/project/setup.py
      - ./data:/data
    environment:
      FLASK_APP: hets_api
      FLASK_ENV: development

  hets:
    image: spechub2/hets:latest
    networks:
      - bridge
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data/amalgamation
      - ./Hets-lib:/data/hets
    environment:
      HETS_LIB: /data

  innovator:
    build:
      context: ./concept-innovator
      dockerfile: Dockerfile.dev
    networks:
      - bridge
    ports:
      - "3000:5000"
    volumes:
      - ./concept-innovator/concept_innovator:/opt/project/concept_innovator
      - ./concept-innovator/tests:/opt/project/tests
      - ./concept-innovator/setup.py:/opt/project/setup.py
    environment:
      FLASK_APP: concept_innovator
      FLASK_ENV: development

  thesis:
    build: ./thesis
    volumes:
      - ./thesis:/opt/thesis
      - thesis_html:/opt/thesis/out/html

  frontend:
    image: danlynn/ember-cli:latest
    volumes:
      - ./frontend:/myapp
      - frontend_pkgs:/myapp/node_modules
      - thesis_html:/myapp/public/thesis
    tmpfs:
      - /myapp/tmp
    ports:
      - "4200:4200"
      - "7020:7020"
      - "7357:7357"

volumes:
  frontend_pkgs:
  thesis_html:

networks:
  bridge:
    driver: bridge
