version: "3"

services:

  amalgamation:
    volumes:
      - spec_data:/data

  hets-api:
    volumes:
      - spec_data:/opt/data

  specifier:
    environment:
      MAX_FACTS_PER_RELATION: 5
      VALID_FACT_LANGUAGES: 'en,de'

  frontend:
    command: ember build -prod
    volumes:
      - frontend_dist:/opt/project/dist

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_dist:/usr/share/nginx/frontend
      - thesis_html:/usr/share/nginx/thesis

volumes:
  frontend_dist:
  spec_data: