version: "3"

services:

  amalgamation:
    build: ./amalgamation
    networks:
      - bridge
    ports:
      - "4000:5000"
    environment:
      HETSAPI_HOST: hets-api:5000
    depends_on:
      - hets-api

  hets-api:
    build: ./hets-api
    networks:
      - bridge
    ports:
      - "5000:5000"
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - HETS_EXECUTABLE=/opt/Hets/hets

  specifier:
    build: ./specifier
    networks:
      - bridge
    ports:
      - "3000:5000"
    environment:
      MAX_FACTS_PER_RELATION: 1
      VALID_FACT_LANGUAGES: 'en,de'
      CONCEPTNET_HOST: 'api.conceptnet.io'

  thesis:
    build: ./thesis
    volumes:
      - thesis_html:/opt/thesis/out/html

  frontend:
    build: ./frontend
    environment:
      SPECIFIER_HOST: localhost:3000
      AMALGAMATION_HOST: localhost:4000

volumes:
  frontend_pkgs:
  thesis_html:

networks:
  bridge:
    driver: bridge
