version: "3"

services:
  amalgamation:
    build:
      context: ./amalgamation
      dockerfile: Dockerfile.dev
    networks:
      - bridge
    ports:
      - "4000:5000"
    volumes:
      - ./amalgamation:/opt/project
      - ./data:/data
    environment:
      HETSAPI_INTERNAL_URL: hets-api:5000
      FLASK_APP: amalgamation
      FLASK_ENV: development
    depends_on:
      - hets-api

  hets-api:
    build:
      context: ./hets-api
      dockerfile: Dockerfile.dev
    networks:
      - bridge
    ports:
      - "5000:5000"
    volumes:
      - ./hets-api:/opt/project
      - ./data:/data
    environment:
      FLASK_APP: hets_api
      FLASK_ENV: development

  hets:
    image: spechub2/hets:latest
    networks:
      - bridge
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data/amalgamation
    environment:
      HETS_LIB: /data

  specifier:
    build:
      context: ./specifier
      dockerfile: Dockerfile.dev
    networks:
      - bridge
    ports:
      - "3000:5000"
    volumes:
      - ./specifier:/opt/project
    environment:
      FLASK_APP: concept_specifier
      FLASK_ENV: development
      AMALGAMATION_INTERNAL_HOST: amalgamation:5000

  thesis:
    build: ./thesis
    volumes:
      - ./thesis:/opt/thesis
      - thesis_html:/opt/thesis/out/html

  frontend:
    image: danlynn/ember-cli:latest
    volumes:
      - ./frontend:/myapp
      - frontend_pkgs:/myapp/node_modules
      - thesis_html:/myapp/public/thesis
    tmpfs:
      - /myapp/tmp
    ports:
      - "4200:4200"
      - "7020:7020"
      - "7357:7357"
    environment:
      SPECIFIER_HOST: localhost:3000
      AMALGAMATION_HOST: localhost:4000

volumes:
  frontend_pkgs:
  thesis_html:

networks:
  bridge:
    driver: bridge
